spring:
  profiles:
    active: set1 # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8080