spring:
  profiles:
    active: set1 # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# actuator 설정: datasource 확인을 위한 /env 설정 확인
endpoints:
  env:
    enabled: true
management:
  security:
    enabled: false

# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db
